apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: prod
  labels:
    app: user-service
type: Opaque
data:
  # Base64 encoded credentials
  # username: merako34
  # password: tu_token_de_docker_hub
  docker-username: bWVyYWtvMzQ=
  docker-password: ZGNrcl9wYXRfRHpWZzlYazZSbDc4ZmV4THBRU0E0Rm11S2Fr