apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: prod
  labels:
    app: config-server
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
  - name: http
    port: 8888
    targetPort: 8888
    protocol: TCP
