# proxy-client-deployment.yaml (PROD)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: prod
  labels:
    app: proxy-client
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - proxy-client
              topologyKey: kubernetes.io/hostname
      containers:
      - name: proxy-client
        image: merako34/proxy-client:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8200
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_APPLICATION_NAME
          value: "PROXY-CLIENT"
        - name: SPRING_CONFIG_LOCATION
          value: "file:/config/application-prod.yml"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8200
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8200
          initialDelaySeconds: 90
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: proxy-client-config