# service-discovery-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: stage
  labels:
    app: service-discovery
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
  - name: http
    port: 8761
    targetPort: 8761
    protocol: TCP