apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: stage
  labels:
    app: order-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: v1
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
      - name: order-service
        image: merako34/order-service:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8300
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        - name: SPRING_APPLICATION_NAME
          value: "ORDER-SERVICE"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"