apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: dev
  labels:
    app: user-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
      - name: user-service
        image: merako34/user-service:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8700
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_APPLICATION_NAME
          value: "USER-SERVICE"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 20
          periodSeconds: 5