# payment-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: prod
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - name: http
    port: 8400
    targetPort: 8400
    protocol: TCP