apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: dev
  labels:
    app: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - name: http
    port: 8700
    targetPort: 8700
    protocol: TCP