apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
  namespace: stage
  labels:
    app: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
  - name: http
    port: 8500
    targetPort: 8500
    protocol: TCP