apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
  namespace: prod
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
  - name: http
    port: 8300
    targetPort: 8300
    protocol: TCP