apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: dev
  labels:
    app: shipping-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
        version: v1
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: shipping-service
          image: merako34/shipping-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8600
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_APPLICATION_NAME
              value: "SHIPPING-SERVICE"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
        