apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
  namespace: dev
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8400
      targetPort: 8400
      protocol: TCP

