apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: stage
  labels:
    app: user-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      imagePullSecrets:
      - name: dockerhub-credentials
      containers:
      - name: user-service
        image: merako34/user-service:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8700
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        - name: SPRING_APPLICATION_NAME
          value: "USER-SERVICE"
        - name: SPRING_CONFIG_LOCATION
          value: "file:/config/application-stage.yml"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 420
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8700
          initialDelaySeconds: 240
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: user-service-config