apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: prod
  labels:
    app: product-service
type: Opaque
data:
  docker-username: bWVyYWtvMzQ=
  docker-password: ZGNrcl9wYXRfRHpWZzlYazZSbDc4ZmV4THBRU0E0Rm11S2Fr