# product-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: prod
  labels:
    app: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
  - name: http
    port: 8500
    targetPort: 8500
    protocol: TCP