apiVersion: v1
kind: Service
metadata:
  name: favourite-service-svc
  namespace: dev
  labels:
    app: favourite-service
spec:
  type: ClusterIP
  selector:
    app: favourite-service
  ports:
    - name: http
      port: 88
      targetPort: 88
      protocol: TCP