apiVersion: v1
kind: Service
metadata:
  name: shipping-service-svc
  namespace: dev
  labels:
    app: shipping-service
spec:
  type: ClusterIP
  selector:
    app: shipping-service
  ports:
    - name: http
      port: 8600
      targetPort: 8600
      protocol: TCP