apiVersion: v1
kind: Service
metadata:
  name: favourite-service-svc
  namespace: prod
  labels:
    app: favourite-service
spec:
  type: ClusterIP
  selector:
    app: favourite-service
  ports:
    - name: http
      port: 8800
      targetPort: 8800
      protocol: TCP