# service-discovery-deployment.yaml (PROD)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: prod
  labels:
    app: service-discovery
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - service-discovery
              topologyKey: kubernetes.io/hostname
      containers:
      - name: service-discovery
        image: merako34/service-discovery:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_APPLICATION_NAME
          value: "SERVICE-DISCOVERY"
        - name: SPRING_CONFIG_LOCATION
          value: "file:/config/application-prod.yml"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 90
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: service-discovery-config