# service-discovery-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: prod
  labels:
    app: service-discovery
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        version: v1
    spec:
      imagePullSecrets:
      - name: dockerhub-credentials
      containers:
      - name: service-discovery
        image: merako34/service-discovery:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_APPLICATION_NAME
          value: "SERVICE-DISCOVERY"
        - name: SPRING_CONFIG_LOCATION
          value: "file:/config/application-prod.yml"
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: service-discovery-config