# service-discovery-service.yaml (PROD)
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: prod
  labels:
    app: service-discovery
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
  - name: http
    port: 8761
    targetPort: 8761
    protocol: TCP